import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Logo from "../../public/logo.svg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuItems: {
  label: string;
  href: string;
}[] = [
  {
    href: "/",
    label: "Home",
  },
  {
    href: "/to-negative",
    label: "To Negative",
  },
  {
    href: "/subtraction",
    label: "Subtraction",
  },
  {
    href: "/multiplication",
    label: "Multiplication",
  },
  {
    href: "/division",
    label: "Division",
  },
];

const Sidebar = () => {
  return (
    <div className="bg-base-200">
      <div className="mx-auto text-center my-2">
        <a
          href="https://devfitra.com"
          className="btn btn-ghost normal-case text-xl"
          target="_blank"
        >
          <img height={32} width="auto" className="h-8 w-auto" src={Logo.src} />
          DevFitra
        </a>
      </div>
      <ul className="menu menu-md w-56">
        {menuItems.map((item, index) => (
          <li key={index}>
            <a href={item.href}>{item.label}</a>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  if (typeof window !== "undefined") return;

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen">
          <Sidebar />
          <div className="bg-base-100 flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
